defaults:
  - _self_
  #- early_stopping.yaml
  - learning_rate_monitor.yaml
  - time_tracking.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - model_checkpoint.yaml #topk=0 if not wanted!
  #- metric_collector.yaml
