model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/callback_checkpoints
  filename: ${module.network.model_name}_${datamodule.dataset.hf_name}_{epoch:02d}
  monitor: "val/BCEWithLogitsLoss" 
  verbose: False
  save_last: False #file: last.ckpt
  save_top_k: 2
  mode: "min"
  auto_insert_metric_name: False
  save_weights_only: False
  every_n_train_steps: null
  train_time_interval: null
  every_n_epochs: null
  save_on_train_epoch_end: null
