# @package _global_
defaults:
  - _self_
  - datamodule: HSN
  - module: multilabel
  - callbacks: default
  - paths: default
  - trainer: single_gpu
  - logger: wandb_default
  - hydra: default
  - extras: default

  - experiment: null
  - hparams_search: null
  - debug: null

  - override datamodule/transforms/waveform_augmentations: none.yaml
  - override datamodule/transforms/spectrogram_augmentations: none.yaml

task_name: "train"
ckpt_path: null
seed: 1

module:
  network: efficientnet
logger:
  wandb:
    mode: online

train: True
test: True
save_state_dict: True
start_time: ${now:%Y-%m-%d_%H%M%S}
dump_metrics: True
