#POW powdermill nature
_target_: birdset.datamodule.inference_datamodule.InferenceDataModule

defaults: 
  - _self_
  - transforms: bird_default.yaml
  - loaders: default.yaml
  - mapper: xc_bambird_mapper.yaml

dataset:
  data_dir: ${paths.dataset_path}
  hf_path: DBD-research-group/BirdSet
  hf_name: POW
  seed: ${seed}
  n_classes: 48
  n_workers: 1
  val_split: 0.2
  task: ${module.task}
  subset: null
  sampling_rate: ${module.network.sampling_rate}
  class_weights_loss: null
  class_weights_sampler: null
  classlimit: 500
  eventlimit: 5