model: 
  _target_: birdset.modules.models.birdnet.BirdNetModel
  num_classes: ${datamodule.dataset.n_classes}
  model_path: ${paths.root_dir}/resources/birdnet/BirdNET_GLOBAL_6K_V2.4_Model # Can be downloaded here: https://github.com/kahst/BirdNET-Analyzer/tree/main/checkpoints/V2.4
  train_classifier: False
  restrict_logits: True
  label_path: ${paths.root_dir}/resources/birdnet/label_ebird.csv
  pretrain_info:
    hf_path: ${datamodule.dataset.hf_path}
    hf_name: ${datamodule.dataset.hf_name}
    hf_pretrain_name: null

model_name: birdnet
model_type: waveform
torch_compile: False
sampling_rate: 48_000
normalize_spectrogram: False
normalize_waveform: null