model:
  _target_: birdset.modules.models.convnext.ConvNextClassifier
  num_classes: null
  num_channels: 1
  checkpoint: facebook/convnext-base-224-22k
  local_checkpoint: null
  cache_dir: ${paths.dataset_path}/models/
  pretrain_info:
    hf_path: ${datamodule.dataset.hf_path}
    hf_name: ${datamodule.dataset.hf_name}
    hf_pretrain_name: null
    valid_test_only: False

model_name: convnext
model_type: vision
torch_compile: False
sampling_rate: 32_000
normalize_waveform: null
normalize_spectrogram: True













