model:
  _target_: birdset.modules.models.efficientnet.EfficientNetClassifier
  num_classes: null
  num_channels: 1
  checkpoint: google/efficientnet-b1
  local_checkpoint: null
  cache_dir: ${paths.dataset_path}/models/
  pretrain_info:
    hf_path: ${datamodule.dataset.hf_path}
    hf_name: ${datamodule.dataset.hf_name}
    hf_pretrain_name: null
    valid_test_only: False

model_name: efficientnet
model_type: vision
torch_compile: False
sampling_rate: 32_000
normalize_waveform: null
normalize_spectrogram: True













