model:
  _target_: birdset.modules.models.hubert.HubertSequenceClassifier
  checkpoint: facebook/hubert-base-ls960
  local_checkpoint: null
  num_classes: null
  cache_dir: ${paths.model_path}
  pretrain_info:
    hf_path: ${datamodule.dataset.hf_path}
    hf_name: ${datamodule.dataset.hf_name}
    hf_pretrain_name: null
    valid_test_only: False
  
model_name: hubert
model_type: raw
torch_compile: False
sampling_rate: 16_000

# hubert uses the w2v2 featue extractor 






