model:
  _target_: birdset.modules.models.resnet.ResNetClassifier
  baseline_architecture: 'resnet18'
  num_classes: null
  num_channels: 1
  pretrained: True
  pretrain_info: null

model_name: resnet18
model_type: vision
torch_compile: False
sampling_rate: 32_000
normalize_waveform: null
normalize_spectrogram: True