root_dir: ${oc.env:PROJECT_ROOT}
work_dir: ${hydra:runtime.cwd}

# dynamic output directory
# store ckpts etc. 
output_dir: ${hydra:runtime.output_dir}

# data directory
dataset_path: /mnt/work/bird2vec/birdset_hf_download/${datamodule.dataset.hf_name}
model_path: /mnt/work/bird2vec/birdset_hf_download/models
background_path: /mnt/work/bird2vec/data/dcase18/wav

# logging directory, has to be static to work properly
log_dir: /mnt/work/bird2vec/birdset_logs/