time_masking:
    _target_: torchvision.transforms.RandomApply
    p: 0.3
    transforms: # - _ --> list!
      - _target_: torchaudio.transforms.TimeMasking
        time_mask_param: 100
        iid_masks: True