_target_: lightning.Trainer
default_root_dir: paths.output_dir

min_epochs: 1
max_epochs: 10

accelerator: "cpu"
devices: 1

enable_checkpointing: True
fast_dev_run: false

strategy: "auto"
deterministic: false

gradient_clip_val: 0.5
#stochastic_weight_avg: True
accumulate_grad_batches: 1
precision: 16