background_noise:
  #_target_: torch_audiomentations.AddBackgroundNoise
  _target_: birdset.datamodule.components.augmentations.AddBackgroundNoise
  p: 0.5
  min_snr_in_db: 3
  max_snr_in_db: 30
  sample_rate: ${module.network.sampling_rate}
  target_rate: ${module.network.sampling_rate}
  background_paths: ${paths.background_path}



