_target_: birdset.datamodule.LoadersConfig
train:
  _target_: birdset.datamodule.LoaderConfig
  batch_size: 8
  shuffle: True
  num_workers: 4
  drop_last: False
  persistent_workers: True
  pin_memory: False

valid:
  _target_: birdset.datamodule.LoaderConfig
  batch_size: 8
  shuffle: False
  num_workers: 4
  drop_last: False
  persistent_workers: True
  pin_memory: False

test:
  _target_: birdset.datamodule.LoaderConfig
  batch_size: 8
  shuffle: False
  num_workers: 4
  drop_last: False
  pin_memory: False