# defaults: 
#   - override hydra_logging: colorlog
#   - override job_logging: colorlog 

job:
  chdir: True
run:
  dir: ${paths.log_dir}/${task_name}/runs/${datamodule.dataset.hf_name}/${module.network.model_name}/${seed}${now:%Y-%m-%d_%H%M%S}
  
  
  
