_target_: birdset.datamodule.components.transforms.BirdSetTransformsWrapper
sampling_rate: ${module.network.sampling_rate}
model_type: ${module.network.model_type}
task: ${datamodule.dataset.task}

defaults:
  - _self_
  - decoding: null
  - feature_extractor: null

preprocessing:
  normalize_waveform: "instance_min_max"
  use_spectrogram: False

waveform_augmentations:
  Gain:
    _target_: torch_audiomentations.Gain
    p: 0.5
    min_gain_in_db: -6
    max_gain_in_db: 2.3
  PolarityInversion:
    _target_: torch_audiomentations.PolarityInversion
    p: 0.5
  Shift:
    _target_: torch_audiomentations.Shift
    p: 0.5
    min_shift: -0.1
    max_shift: 0.1
    shift_unit: "seconds"