_target_: birdset.datamodule.components.transforms.EmbeddingTransforms
sampling_rate: ${module.network.sampling_rate}
task: ${datamodule.dataset.task}
max_length: ${module.network.model.embedding_model.window_size_s} # Attention: this might not work with any model!! -> You must specify it or set to 5s as its done in code
  



