_target_: birdset.datamodule.components.transforms.BirdSetTransformsWrapper
sampling_rate: ${module.network.sampling_rate}
model_type: ${module.network.model_type}
task: ${datamodule.dataset.task}

defaults:
  - _self_
  - preprocessing: default.yaml 
  - waveform_augmentations: null
  - spectrogram_augmentations: default.yaml
  - decoding: null
  



